"""Generated seat file bodies for `workforce hire --provider ...` (D13).

``launch.py`` is provider-agnostic except for a small planting step some
providers need before exec: cursor reads its MCP servers and permissions
from ``<cwd>/.cursor`` and grok reads its MCP servers from
``<cwd>/.grok/config.toml`` — both only from the folder the CLI is actually
launched in, which is the prepared checkout task_runner hands the process,
not this seat folder. The launcher plants the seat's own copy there before
exec (never overwriting an existing task's settings) so the seat signs
WorkLane as itself instead of falling back to a user-scope config, on both
the first dispatch and engine-mediated recovery. The planted files are also
appended to the checkout worktree's git info/exclude so a seat's own `git
add` never commits them.
"""

from __future__ import annotations

import json
from typing import Any, Dict, Iterable, List

LAUNCH_PY = '''import sys
from pathlib import Path
from workforce.task_runner import main as task_runner_main
h=Path(__file__).parent
argv=list(sys.argv[1:])
while '--config' in argv:
    i=argv.index('--config'); del argv[i:i+2]
raise SystemExit(task_runner_main(['--config',str(h/'runner.json')]+argv))
'''

LAUNCH_PY_CURSOR = '''import sys
from pathlib import Path
from workforce.task_runner import main as task_runner_main
h=Path(__file__).parent
argv=list(sys.argv[1:])
while '--config' in argv:
    i=argv.index('--config'); del argv[i:i+2]
SETTINGS=(('mcp.json','.cursor/mcp.json'),('permissions.json','.cursor/cli.json'))
EXCLUDES=['.cursor/']
from workforce.task_runner import exclude_from_git

def _plant_settings(config,result):
    checkout=Path(result['checkout'])
    for source,destination in SETTINGS:
        src=h/source; dst=checkout/destination
        if not src.is_file():
            raise ValueError('provider settings are missing: '+source)
        if dst.exists() and dst.read_bytes()!=src.read_bytes():
            raise ValueError('preserved provider settings differ; review before resuming')
        dst.parent.mkdir(parents=True,exist_ok=True)
        if not dst.exists(): dst.write_bytes(src.read_bytes())
    exclude_from_git(str(checkout),EXCLUDES)

raise SystemExit(task_runner_main(['--config',str(h/'runner.json')]+argv,before_exec=_plant_settings))
'''

LAUNCH_PY_GROK = '''import sys
from pathlib import Path
from workforce.task_runner import main as task_runner_main
h=Path(__file__).parent
argv=list(sys.argv[1:])
while '--config' in argv:
    i=argv.index('--config'); del argv[i:i+2]
SETTINGS=(('.grok/config.toml','.grok/config.toml'),)
EXCLUDES=['.grok/']
from workforce.task_runner import exclude_from_git

def _plant_settings(config,result):
    checkout=Path(result['checkout'])
    for source,destination in SETTINGS:
        src=h/source; dst=checkout/destination
        if not src.is_file():
            raise ValueError('provider settings are missing: '+source)
        if dst.exists() and dst.read_bytes()!=src.read_bytes():
            raise ValueError('preserved provider settings differ; review before resuming')
        dst.parent.mkdir(parents=True,exist_ok=True)
        if not dst.exists(): dst.write_bytes(src.read_bytes())
    exclude_from_git(str(checkout),EXCLUDES)

raise SystemExit(task_runner_main(['--config',str(h/'runner.json')]+argv,before_exec=_plant_settings))
'''

CONTRACT_TEMPLATE = """# {project} bounded implementation contract ({provider} seat)

Generated by `workforce hire --provider {provider}`. Do
not hand-edit the command shape here — regenerate with
`workforce hire {slug} --regenerate` instead.

Identity {identity}; project {project}. Manual single-pass implementation
under WorkForce budget; dispatched by the host or a bounded supervisor. Read
the workspace AGENTS.md and the prepared checkout's AGENTS.md before
editing. Claim the selected ready order through the dedicated WorkLane MCP
before edits; never sign as You. Implement only in the prepared checkout
and only within the order's Where and In scope. Tests use disposable
workspaces only; never open the live WorkLane stores for writing, never
dispatch a provider, never restart a service. No other product files, host
configuration, rosters, credentials, runtime data, merges, releases,
deployment or private history publication. Preserve dirty work and stop on
permission or authentication failures or three no-progress corrections.
Commit only explicit owned files in the prepared branch; the host
publishes, reviews, integrates and installs. Record tests and revision on
the same order with wl_comment and park with wl_park; the evidence-only MCP
profile does not close work. If this seat is configured for continuity, save an
owner-signed wl_checkpoint after meaningful verified edits and before planned
budget stops or parking: record actual source/instruction revisions, artifact
hashes and the next action. Never invent missing facts or transfer ownership
yourself; the qualified host recovery path owns handoff. Verify with: {test_commands}. Vendor CLI:
{provider}. Model/effort pin: {model_display}. This contract does not
authorize subagents or bypassing permissions.

## Never touch

- Anything gated for human decision — prepare, never ship.
- `local/roster.json` and other employment records.
- `--dangerously-skip-permissions` / `--force` / `--yolo` / equivalent —
  this seat's command never carries a permission-bypass flag; do not add
  one.
"""

# {authority}/{task_id}/{checkout}/{branch} are task_runner's own
# placeholders (workforce/task_runner.py:_render) — escaped as {{ }} here so
# this module's own .format() pass leaves them untouched for task_runner to
# fill in at prepare()/recover() time, one per dispatched shift.
PROMPT_TEMPLATE = """{{authority}}
Selected task {{task_id}}, project {project}, worker {identity}. Prepared \
checkout {{checkout}}; branch {{branch}}. Use the dedicated MCP wl_show \
then wl_claim before editing. Read the project's AGENTS.md at the repo \
root. Complete the ticket's acceptance in this checkout. Verify with: \
{test_commands}. Inspect the exact diff, commit explicit files, record \
evidence with wl_comment and park via wl_park. Do not merge, publish, \
deploy or modify any host or other product. Use tools directly; no \
subagents. Return a concise final result. If blocked, preserve everything \
and report honestly.
"""


def render_launch_py(provider: str = "") -> str:
    if provider == "cursor":
        return LAUNCH_PY_CURSOR
    if provider == "grok":
        return LAUNCH_PY_GROK
    return LAUNCH_PY


def render_contract(
    *, slug: str, identity: str, provider: str, model: str, project: str,
    test_commands: str, land_it: str = "",
) -> str:
    return CONTRACT_TEMPLATE.format(
        slug=slug, identity=identity, provider=provider,
        model_display=model or "vendor default", project=project,
        test_commands=test_commands or "the project's test suite",
    )


def render_prompt(
    *, slug: str = "", identity: str, project: str, contract_path: str = "",
    test_commands: str, land_it_prompt: str = "",
) -> str:
    return PROMPT_TEMPLATE.format(
        identity=identity, project=project,
        test_commands=test_commands or "the project's test suite",
    )


def render_mcp_json(
    *, identity: str, worklane_python: str, worklane_runtime_dir: str,
) -> Dict[str, Any]:
    return {
        "mcpServers": {
            "worklane": {
                "command": worklane_python,
                "args": ["-m", "worklane.mcp", "--author", identity],
                "env": {
                    "WL_AGENT_ID": identity,
                    "WORKLANE_RUNTIME_DIR": worklane_runtime_dir,
                    "WORKLANE_COMMENT_TRANSITIONS": "0",
                },
            }
        }
    }


def render_mcp_json_text(**kwargs: Any) -> str:
    return json.dumps(render_mcp_json(**kwargs), indent=2) + "\n"


# The full wl_* surface — anything not in a seat's own allow list is denied
# explicitly so a permissions file never has to be re-read to know a tool is
# blocked (cursor's cli.json permissions model, wf-261 gap 15).
_ALL_WORKLANE_TOOLS = (
    "wl_show", "wl_ready", "wl_claim", "wl_comment", "wl_park", "wl_checkpoint", "wl_handoff",
    "wl_close", "wl_create", "wl_label", "wl_update",
)


def render_permissions_json(*, mcp_tool_names: Iterable[str]) -> Dict[str, Any]:
    allowed = list(mcp_tool_names)
    denied = [t for t in _ALL_WORKLANE_TOOLS if t not in allowed]
    return {
        "permissions": {
            "allow": [
                "Read(**)", "Write(**)",
                "Shell(git)", "Shell(rg)", "Shell(ls)", "Shell(env)",
                "Shell(python3)",
            ] + ["Mcp(worklane:%s)" % name for name in allowed],
            "deny": [
                "Shell(rm)", "Shell(curl)", "Shell(launchctl)",
                "Write(**/.env*)", "Write(**/*.key)",
            ] + ["Mcp(worklane:%s)" % name for name in denied],
        }
    }


def render_permissions_json_text(**kwargs: Any) -> str:
    return json.dumps(render_permissions_json(**kwargs), indent=2) + "\n"


def render_grok_config_toml(
    *, identity: str, worklane_python: str, worklane_runtime_dir: str,
) -> str:
    return (
        "# Project-scoped Grok CLI config for the {identity} seat.\n"
        "# Loaded when grok runs with this folder as its working directory; "
        "overrides the\n"
        "# user-scope server of the same name so the seat signs WorkLane as "
        "itself, never as You.\n\n"
        "[mcp_servers.worklane]\n"
        'command = "{worklane_python}"\n'
        'args = ["-m", "worklane.mcp", "--author", "{identity}"]\n'
        'env = {{ WL_AGENT_ID = "{identity}", TP_AGENT_ID = "{identity}", '
        'WORKLANE_RUNTIME_DIR = "{worklane_runtime_dir}", '
        'WORKLANE_COMMENT_TRANSITIONS = "0" }}\n'
        "enabled = true\n"
    ).format(
        identity=identity, worklane_python=worklane_python,
        worklane_runtime_dir=worklane_runtime_dir,
    )
