"""Generated seat file bodies for `workforce hire --provider ...` (D13).

``launch.py`` is provider-agnostic (task_runner reads the provider command
from runner.json), so one template covers all four providers.
"""

from __future__ import annotations

import json
from typing import Any, Dict, List

LAUNCH_PY = '''import json,os,subprocess,sys
from pathlib import Path
from workforce.task_runner import prepare,_acquire_lock,main as task_runner_main
h=Path(__file__).parent
# Engine-mediated recovery: forward operator recovery flags to task_runner
# unchanged. The roster command carries --config runner.json so the engine
# can resolve state_dir; strip it here.
argv=list(sys.argv[1:])
while '--config' in argv:
    i=argv.index('--config'); del argv[i:i+2]
if argv:
    raise SystemExit(task_runner_main(['--config',str(h/'runner.json')]+argv))
result=prepare(json.loads((h/'runner.json').read_text()))
if result is None:raise SystemExit(0)
lock_fd=_acquire_lock(result['lock'])
raise SystemExit(subprocess.call(result['argv'],cwd=result['checkout'],env=dict(os.environ)))
'''

CONTRACT_TEMPLATE = """# {slug} — Employment Contract (L2, generated)

Generated by `workforce hire --provider {provider}` (AGENT_ADOPTION D13). Do
not hand-edit the command shape here — regenerate with
`workforce hire {slug} --regenerate` instead.

## Identity

- Signs all work as: `{identity}`
- Vendor CLI: {provider}
- Model/effort pin: {model_display}

## Lane — what this worker may claim

- Tickets labeled `worker:{slug}` in store `{project}`, and nothing else.

## Never touch

- Anything behind a citizen gate (L0/L1) — prepare, never ship.
- `local/roster.json` and other employment records.
- `--dangerously-skip-permissions` / `--force` / `--yolo` / equivalent —
  this seat's command never carries a permission-bypass flag; do not add one.

## Procedure

1. Claim — set the ticket in progress under your identity.
2. Work — smallest slice; stage only files your contract allows.
3. Verify — run: {test_commands}
4. Land it — {land_it}
5. Close out — comment and hand back; include the landing SHA under Links.
"""

PROMPT_TEMPLATE = """You are `{identity}` on **{project}**. Sign as `{identity}`.

1. Read your contract: `{contract_path}`.
2. Read the project instructions: `AGENTS.md` at the repo root.
3. Check the queue: tickets labeled `worker:{slug}` in store `{project}` only.
4. Do ONE slice of ONE ticket. Sign everything as `{identity}`.
5. Verify with: {test_commands}
6. Queue empty or stop rule hit: stop cleanly and say why.

Land it before close-out: {land_it_prompt}
"""


def render_launch_py() -> str:
    return LAUNCH_PY


def render_contract(
    *, slug: str, identity: str, provider: str, model: str, project: str,
    test_commands: str, land_it: str,
) -> str:
    return CONTRACT_TEMPLATE.format(
        slug=slug, identity=identity, provider=provider,
        model_display=model or "vendor default", project=project,
        test_commands=test_commands or "the project's test suite",
        land_it=land_it,
    )


def render_prompt(
    *, slug: str, identity: str, project: str, contract_path: str,
    test_commands: str, land_it_prompt: str,
) -> str:
    return PROMPT_TEMPLATE.format(
        slug=slug, identity=identity, project=project,
        contract_path=contract_path,
        test_commands=test_commands or "the project's test suite",
        land_it_prompt=land_it_prompt,
    )


def render_mcp_json(
    *, identity: str, worklane_python: str, worklane_runtime_dir: str,
) -> Dict[str, Any]:
    return {
        "mcpServers": {
            "worklane": {
                "command": worklane_python,
                "args": ["-m", "worklane.mcp", "--author", identity],
                "env": {
                    "WL_AGENT_ID": identity,
                    "WORKLANE_RUNTIME_DIR": worklane_runtime_dir,
                    "WORKLANE_COMMENT_TRANSITIONS": "0",
                },
            }
        }
    }


def render_mcp_json_text(**kwargs: Any) -> str:
    return json.dumps(render_mcp_json(**kwargs), indent=2) + "\n"
