"""Generated seat file bodies for `workforce hire --provider ...` (D13).

``launch.py`` is provider-agnostic except for a small planting step some
providers need before exec: cursor reads its MCP servers and permissions
from ``<cwd>/.cursor`` and grok reads its MCP servers from
``<cwd>/.grok/config.toml`` — both only from the folder the CLI is actually
launched in, which is the prepared checkout task_runner hands the process,
not this seat folder. The launcher plants the seat's own copy there before
exec (never overwriting an existing task's settings) so the seat signs
WorkLane as itself instead of falling back to a user-scope config, on both
the first dispatch and engine-mediated recovery. The planted files are also
appended to the checkout worktree's git info/exclude so a seat's own `git
add` never commits them.
"""

from __future__ import annotations

import json
from typing import Any, Dict, Iterable, List

LAUNCH_PY = '''import json,os,subprocess,sys
from pathlib import Path
from workforce.task_runner import prepare,_acquire_lock,main as task_runner_main
h=Path(__file__).parent
# Engine-mediated recovery: forward operator recovery flags to task_runner
# unchanged. The roster command carries --config runner.json so the engine
# can resolve state_dir; strip it here.
argv=list(sys.argv[1:])
while '--config' in argv:
    i=argv.index('--config'); del argv[i:i+2]
if argv:
    raise SystemExit(task_runner_main(['--config',str(h/'runner.json')]+argv))
result=prepare(json.loads((h/'runner.json').read_text()))
if result is None:raise SystemExit(0)
lock_fd=_acquire_lock(result['lock'])
raise SystemExit(subprocess.call(result['argv'],cwd=result['checkout'],env=dict(os.environ)))
'''

LAUNCH_PY_CURSOR = '''import json,os,subprocess,sys
from pathlib import Path
from workforce.task_runner import prepare,_acquire_lock,exclude_from_git,main as task_runner_main
h=Path(__file__).parent
# Engine-mediated recovery: forward operator recovery flags to task_runner
# unchanged. The roster command carries --config runner.json so the engine
# can resolve state_dir; strip it here.
argv=list(sys.argv[1:])
while '--config' in argv:
    i=argv.index('--config'); del argv[i:i+2]
def _plant_cursor(checkout):
    # cursor-agent reads MCP servers and permissions from <cwd>/.cursor, and
    # the provider runs inside the prepared checkout; plant the seat's own
    # identity there so it signs WorkLane as itself. Never overwrite existing
    # task settings, and never let the plant land in the seat's own commit.
    if not checkout: return
    _settings=Path(checkout)/'.cursor'; _settings.mkdir(exist_ok=True)
    for _src,_dst in (('mcp.json','mcp.json'),('permissions.json','cli.json')):
        _s=h/_src; _d=_settings/_dst
        if _s.exists() and not _d.exists(): _d.write_text(_s.read_text())
    exclude_from_git(checkout,['.cursor/'])
if argv:
    if '--recover-receipt' in argv:
        try: _plant_cursor(json.loads(Path(argv[argv.index('--recover-receipt')+1]).read_text()).get('checkout'))
        except Exception: pass
    raise SystemExit(task_runner_main(['--config',str(h/'runner.json')]+argv))
result=prepare(json.loads((h/'runner.json').read_text()))
if result is None:raise SystemExit(0)
lock_fd=_acquire_lock(result['lock'])
_plant_cursor(result['checkout'])
raise SystemExit(subprocess.call(result['argv'],cwd=result['checkout'],env=dict(os.environ)))
'''

LAUNCH_PY_GROK = '''import json,os,subprocess,sys
from pathlib import Path
from workforce.task_runner import prepare,_acquire_lock,exclude_from_git,main as task_runner_main
h=Path(__file__).parent
# Engine-mediated recovery: forward operator recovery flags to task_runner
# unchanged. The roster command carries --config runner.json so the engine
# can resolve state_dir; strip it here.
argv=list(sys.argv[1:])
while '--config' in argv:
    i=argv.index('--config'); del argv[i:i+2]
def _drop_grok_config(checkout):
    import shutil
    cfg=h/'.grok'/'config.toml'
    if not cfg.exists() or not checkout: return
    dst=Path(checkout)/'.grok'; dst.mkdir(exist_ok=True)
    dst_cfg=dst/'config.toml'
    # Never overwrite an existing task-provided config.toml in the checkout.
    if not dst_cfg.exists(): shutil.copy(cfg,dst_cfg)
    exclude_from_git(checkout,['.grok/'])
if argv:
    if '--recover-receipt' in argv:
        try: _drop_grok_config(json.loads(Path(argv[argv.index('--recover-receipt')+1]).read_text()).get('checkout'))
        except Exception: pass
    raise SystemExit(task_runner_main(['--config',str(h/'runner.json')]+argv))
result=prepare(json.loads((h/'runner.json').read_text()))
if result is None:raise SystemExit(0)
lock_fd=_acquire_lock(result['lock'])
_drop_grok_config(result['checkout'])
raise SystemExit(subprocess.call(result['argv'],cwd=result['checkout'],env=dict(os.environ)))
'''

CONTRACT_TEMPLATE = """# {project} bounded implementation contract ({provider} seat)

Generated by `workforce hire --provider {provider}` (AGENT_ADOPTION D13). Do
not hand-edit the command shape here — regenerate with
`workforce hire {slug} --regenerate` instead.

Identity {identity}; project {project}. Manual single-pass implementation
under WorkForce budget; dispatched by the host or a bounded supervisor. Read
the workspace AGENTS.md and the prepared checkout's AGENTS.md before
editing. Claim the selected ready order through the dedicated WorkLane MCP
before edits; never sign as You. Implement only in the prepared checkout
and only within the order's Where and In scope. Tests use disposable
workspaces only; never open the live WorkLane stores for writing, never
dispatch a provider, never restart a service. No other product files, host
configuration, rosters, credentials, runtime data, merges, releases,
deployment or private history publication. Preserve dirty work and stop on
permission or authentication failures or three no-progress corrections.
Commit only explicit owned files in the prepared branch; the host
publishes, reviews, integrates and installs. Record tests and revision on
the same order with wl_comment and park with wl_park; the evidence-only MCP
profile does not close work. Verify with: {test_commands}. Vendor CLI:
{provider}. Model/effort pin: {model_display}. This contract does not
authorize subagents or bypassing permissions.

## Never touch

- Anything behind a citizen gate (L0/L1) — prepare, never ship.
- `local/roster.json` and other employment records.
- `--dangerously-skip-permissions` / `--force` / `--yolo` / equivalent —
  this seat's command never carries a permission-bypass flag; do not add
  one.
"""

# {authority}/{task_id}/{checkout}/{branch} are task_runner's own
# placeholders (workforce/task_runner.py:_render) — escaped as {{ }} here so
# this module's own .format() pass leaves them untouched for task_runner to
# fill in at prepare()/recover() time, one per dispatched shift.
PROMPT_TEMPLATE = """{{authority}}
Selected task {{task_id}}, project {project}, worker {identity}. Prepared \
checkout {{checkout}}; branch {{branch}}. Use the dedicated MCP wl_show \
then wl_claim before editing. Read the project's AGENTS.md at the repo \
root. Complete the ticket's acceptance in this checkout. Verify with: \
{test_commands}. Inspect the exact diff, commit explicit files, record \
evidence with wl_comment and park via wl_park. Do not merge, publish, \
deploy or modify any host or other product. Use tools directly; no \
subagents. Return a concise final result. If blocked, preserve everything \
and report honestly.
"""


def render_launch_py(provider: str = "") -> str:
    if provider == "cursor":
        return LAUNCH_PY_CURSOR
    if provider == "grok":
        return LAUNCH_PY_GROK
    return LAUNCH_PY


def render_contract(
    *, slug: str, identity: str, provider: str, model: str, project: str,
    test_commands: str, land_it: str = "",
) -> str:
    return CONTRACT_TEMPLATE.format(
        slug=slug, identity=identity, provider=provider,
        model_display=model or "vendor default", project=project,
        test_commands=test_commands or "the project's test suite",
    )


def render_prompt(
    *, slug: str = "", identity: str, project: str, contract_path: str = "",
    test_commands: str, land_it_prompt: str = "",
) -> str:
    return PROMPT_TEMPLATE.format(
        identity=identity, project=project,
        test_commands=test_commands or "the project's test suite",
    )


def render_mcp_json(
    *, identity: str, worklane_python: str, worklane_runtime_dir: str,
) -> Dict[str, Any]:
    return {
        "mcpServers": {
            "worklane": {
                "command": worklane_python,
                "args": ["-m", "worklane.mcp", "--author", identity],
                "env": {
                    "WL_AGENT_ID": identity,
                    "WORKLANE_RUNTIME_DIR": worklane_runtime_dir,
                    "WORKLANE_COMMENT_TRANSITIONS": "0",
                },
            }
        }
    }


def render_mcp_json_text(**kwargs: Any) -> str:
    return json.dumps(render_mcp_json(**kwargs), indent=2) + "\n"


# The full wl_* surface — anything not in a seat's own allow list is denied
# explicitly so a permissions file never has to be re-read to know a tool is
# blocked (cursor's cli.json permissions model, wf-261 gap 15).
_ALL_WORKLANE_TOOLS = (
    "wl_show", "wl_ready", "wl_claim", "wl_comment", "wl_park",
    "wl_close", "wl_create", "wl_label", "wl_update",
)


def render_permissions_json(*, mcp_tool_names: Iterable[str]) -> Dict[str, Any]:
    allowed = list(mcp_tool_names)
    denied = [t for t in _ALL_WORKLANE_TOOLS if t not in allowed]
    return {
        "permissions": {
            "allow": [
                "Read(**)", "Write(**)",
                "Shell(git)", "Shell(rg)", "Shell(ls)", "Shell(env)",
                "Shell(python3)",
            ] + ["Mcp(worklane:%s)" % name for name in allowed],
            "deny": [
                "Shell(rm)", "Shell(curl)", "Shell(launchctl)",
                "Write(**/.env*)", "Write(**/*.key)",
            ] + ["Mcp(worklane:%s)" % name for name in denied],
        }
    }


def render_permissions_json_text(**kwargs: Any) -> str:
    return json.dumps(render_permissions_json(**kwargs), indent=2) + "\n"


def render_grok_config_toml(
    *, identity: str, worklane_python: str, worklane_runtime_dir: str,
) -> str:
    return (
        "# Project-scoped Grok CLI config for the {identity} seat "
        "(AGENT_ADOPTION D13).\n"
        "# Loaded when grok runs with this folder as its working directory; "
        "overrides the\n"
        "# user-scope server of the same name so the seat signs WorkLane as "
        "itself, never as You.\n\n"
        "[mcp_servers.worklane]\n"
        'command = "{worklane_python}"\n'
        'args = ["-m", "worklane.mcp", "--author", "{identity}"]\n'
        'env = {{ WL_AGENT_ID = "{identity}", TP_AGENT_ID = "{identity}", '
        'WORKLANE_RUNTIME_DIR = "{worklane_runtime_dir}", '
        'WORKLANE_COMMENT_TRANSITIONS = "0" }}\n'
        "enabled = true\n"
    ).format(
        identity=identity, worklane_python=worklane_python,
        worklane_runtime_dir=worklane_runtime_dir,
    )
